ARG BASE_TAG="1.18.0-rolling-daily"
ARG BASE_IMAGE="core-ubuntu-jammy"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG

USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS=$STARTUPDIR/install
WORKDIR $HOME

######### Install SABnzbd ###########

# Copy installer resources
COPY ./src/ubuntu/install/sabnzbd $INST_SCRIPTS/sabnzbd/

# Run SABnzbd installer
RUN bash $INST_SCRIPTS/sabnzbd/install_sabnzbd.sh && \
    rm -rf $INST_SCRIPTS/sabnzbd/

# Install custom startup script
COPY ./src/ubuntu/install/sabnzbd/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh

######### Single-Application Environment Tweaks ###########

# Replace desktop environment config for single-app mode
RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* \
       $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/

# Replace wallpaper
RUN cp /usr/share/backgrounds/bg_kasm.png /usr/share/backgrounds/bg_default.png

# Remove the panel to enforce single-app experience
RUN apt-get remove -y xfce4-panel

######### Switch to final user context ###########

# Fix permissions for default profile
RUN chown -R 1000:0 $HOME

# Switch HOME to the actual runtime user
ENV HOME /home/kasm-user
WORKDIR $HOME

# Create kasm-user home and prepare SABnzbd config directory
RUN mkdir -p $HOME && \
    mkdir -p $HOME/.sabnzbd && \
    chown -R 1000:0 $HOME

# Copy the sabnzbd.ini from default profile into kasm-user home
# (SABnzbd always reads from the user's .sabnzbd folder)
RUN if [ -f /home/kasm-default-profile/.sabnzbd/sabnzbd.ini ]; then \
        cp /home/kasm-default-profile/.sabnzbd/sabnzbd.ini $HOME/.sabnzbd/ && \
        chown -R 1000:0 $HOME/.sabnzbd; \
    fi

USER 1000
CMD ["--tail-log"]